// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SitemaVoto.Api.Migrations
{
    [DbContext(typeof(SitemaVotoApiContext))]
    [Migration("20260111224651_add-migration nu")]
    partial class addmigrationnu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VotoModelos.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdVotante")
                        .IsUnique();

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("VotoModelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Eslogan")
                        .HasColumnType("text");

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.Property<string>("Partido")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdVotante")
                        .IsUnique();

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("VotoModelos.HistorialResultados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaConsolidacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdOpcionGanadora")
                        .HasColumnType("integer");

                    b.Property<int>("IdProcesoElectoral")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionGanadoraId")
                        .HasColumnType("integer");

                    b.Property<double>("PorcentajeVictoria")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalVotosProcesoElectoral")
                        .HasColumnType("integer");

                    b.Property<int>("VotosGanador")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProcesoElectoral")
                        .IsUnique();

                    b.HasIndex("OpcionGanadoraId");

                    b.ToTable("HistorialResultados");
                });

            modelBuilder.Entity("VotoModelos.OpcionElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("IdProcesoElectoral")
                        .HasColumnType("integer");

                    b.Property<string>("NombreOpcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("OpcionElectorales");
                });

            modelBuilder.Entity("VotoModelos.Papeleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoConfirmacion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdProcesoElectoral")
                        .HasColumnType("integer");

                    b.Property<int>("IdVotante")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<int>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.HasIndex("VotanteId");

                    b.ToTable("Papeletas");
                });

            modelBuilder.Entity("VotoModelos.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("TipoEleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcesoElectorales");
                });

            modelBuilder.Entity("VotoModelos.ResultadoOpcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOpcion")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int?>("OpcionElectoralId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalVotos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcionElectoralId");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("ResultadoOpcion");
                });

            modelBuilder.Entity("VotoModelos.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenVerificacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("VotoModelos.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdOpcionElectoral")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("VotoEncriptado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("VotoModelos.Administrador", b =>
                {
                    b.HasOne("VotoModelos.Votante", "Votante")
                        .WithOne("Administrador")
                        .HasForeignKey("VotoModelos.Administrador", "IdVotante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("VotoModelos.Candidato", b =>
                {
                    b.HasOne("VotoModelos.Votante", "Votante")
                        .WithOne("Candidato")
                        .HasForeignKey("VotoModelos.Candidato", "IdVotante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("VotoModelos.HistorialResultados", b =>
                {
                    b.HasOne("VotoModelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithOne("Historial")
                        .HasForeignKey("VotoModelos.HistorialResultados", "IdProcesoElectoral")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoModelos.OpcionElectoral", "OpcionGanadora")
                        .WithMany()
                        .HasForeignKey("OpcionGanadoraId");

                    b.Navigation("OpcionGanadora");

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("VotoModelos.OpcionElectoral", b =>
                {
                    b.HasOne("VotoModelos.Candidato", null)
                        .WithMany("Opciones")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("VotoModelos.ProcesoElectoral", null)
                        .WithMany("Opciones")
                        .HasForeignKey("ProcesoElectoralId");
                });

            modelBuilder.Entity("VotoModelos.Papeleta", b =>
                {
                    b.HasOne("VotoModelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Papeletas")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoModelos.Votante", "Votante")
                        .WithMany("Papeletas")
                        .HasForeignKey("VotanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesoElectoral");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("VotoModelos.ResultadoOpcion", b =>
                {
                    b.HasOne("VotoModelos.OpcionElectoral", "OpcionElectoral")
                        .WithMany("Resultados")
                        .HasForeignKey("OpcionElectoralId");

                    b.HasOne("VotoModelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("ResultadosPorOpcion")
                        .HasForeignKey("ProcesoElectoralId");

                    b.Navigation("OpcionElectoral");

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("VotoModelos.Voto", b =>
                {
                    b.HasOne("VotoModelos.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Votos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("VotoModelos.Candidato", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("VotoModelos.OpcionElectoral", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("VotoModelos.ProcesoElectoral", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Opciones");

                    b.Navigation("Papeletas");

                    b.Navigation("ResultadosPorOpcion");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotoModelos.Votante", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Candidato");

                    b.Navigation("Papeletas");
                });
#pragma warning restore 612, 618
        }
    }
}
